# Generated by Django 4.1.3 on 2022-12-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introlife_app', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
